# Generated by Django 4.2.7 on 2026-03-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_image_prompt_delete_imageprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
