# Generated by Django 4.2.7 on 2026-03-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('api', '0006_remove_user_created_at_post_topic_post_tone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expiry', to='authtoken.token')),
            ],
            options={
                'db_table': 'token_expiry',
            },
        ),
    ]
