# Generated by Django 4.2.7 on 2026-04-18 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post_approval_note_post_approved_by_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_post_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram')], max_length=20)),
                ('instagram_user_id', models.CharField(max_length=100)),
                ('account_username', models.CharField(max_length=100)),
                ('account_avatar_url', models.URLField(blank=True, default='', max_length=1000)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_accounts',
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
