# Generated by Django 4.2.7 on 2026-04-18 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_auto_publish_post_instagram_post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='account_avatar_url',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='account_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_states',
            },
        ),
    ]
