# Generated by Django 4.2.7 on 2026-04-19 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_socialaccount_account_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_identifier', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encryption_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('user', 'platform', 'instagram_user_id')},
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='account_avatar_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='client_email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='is_client_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='token_last_refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TokenRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_attempted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('error_message', models.CharField(blank=True, default='', max_length=200)),
                ('new_expires_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('pre_expiry', 'Pre-expiry Check')], default='scheduled', max_length=20)),
                ('connected_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_logs', to='api.socialaccount')),
            ],
            options={
                'db_table': 'token_refresh_logs',
                'ordering': ['-refresh_attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail SMTP'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('custom', 'Custom SMTP')], default='gmail', max_length=20)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.EmailField(max_length=254)),
                ('smtp_password_encrypted', models.TextField()),
                ('from_name', models.CharField(max_length=100)),
                ('from_email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_test_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encryption_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_configurations', to='api.encryptionkey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_configurations',
            },
        ),
        migrations.CreateModel(
            name='ClientInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.TextField()),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='api.socialaccount')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='oauthstate',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to='api.clientinvitation'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='encryption_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='social_accounts', to='api.encryptionkey'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('account_connected', 'Instagram Account Connected'), ('account_disconnected', 'Instagram Account Disconnected'), ('invitation_sent', 'Client Invitation Sent'), ('invitation_accepted', 'Client Invitation Accepted'), ('invitation_revoked', 'Client Invitation Revoked'), ('post_published', 'Post Published to Instagram'), ('post_publish_failed', 'Post Publish Failed'), ('token_refreshed', 'Access Token Refreshed'), ('token_expired', 'Access Token Expired'), ('login', 'User Login'), ('logout', 'User Logout'), ('password_changed', 'Password Changed'), ('credentials_updated', 'Credentials Updated')], max_length=50)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace_user', 'created_at'], name='audit_logs_workspa_3369a7_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx')],
            },
        ),
    ]
