# Generated by Django 4.2.7 on 2026-04-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_encryptionkey_alter_socialaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='account_avatar_url',
        ),
        migrations.DeleteModel(
            name='TokenRefreshLog',
        ),
    ]
