# Generated by Django 4.2.7 on 2026-04-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_soft_delete_post_emailconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('specialist', 'Specialist'), ('client', 'Client')], default='specialist', max_length=20),
        ),
    ]
