# Generated by Django 4.2.7 on 2026-04-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_owner_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
    ]
