# Generated by Django 4.2.7 on 2026-04-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notifications_sound_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('account_connected', 'Instagram Account Connected'), ('account_disconnected', 'Instagram Account Disconnected'), ('invitation_sent', 'Client Invitation Sent'), ('invitation_accepted', 'Client Invitation Accepted'), ('invitation_revoked', 'Client Invitation Revoked'), ('post_submitted', 'Post Submitted for Approval'), ('post_approved', 'Post Approved'), ('post_rejected', 'Post Rejected'), ('post_published', 'Post Published to Instagram'), ('post_publish_failed', 'Post Publish Failed'), ('client_removed', 'Client Removed from Workspace'), ('token_refreshed', 'Access Token Refreshed'), ('token_expired', 'Access Token Expired'), ('login', 'User Login'), ('logout', 'User Logout'), ('password_changed', 'Password Changed'), ('credentials_updated', 'Credentials Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_submitted', 'Post Submitted for Review'), ('post_approved', 'Post Approved'), ('post_rejected', 'Post Rejected'), ('post_published', 'Post Published'), ('post_publish_failed', 'Post Publish Failed'), ('post_scheduled_reminder', 'Post Scheduled Reminder'), ('invitation_accepted', 'Invitation Accepted')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='InstagramSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('overview', models.JSONField(default=dict)),
                ('insights', models.JSONField(default=list)),
                ('media', models.JSONField(default=list)),
                ('audience', models.JSONField(default=dict)),
                ('online_followers', models.JSONField(default=dict)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.socialaccount')),
            ],
            options={
                'db_table': 'instagram_snapshots',
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
    ]
