# Generated by Django 4.2.7 on 2026-04-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_instagram_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='analyzer_demo_mode',
            field=models.BooleanField(default=False),
        ),
    ]
