# Generated by Django 4.2.7 on 2026-04-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_analyzer_demo_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
