# Generated by Django 4.2.7 on 2026-04-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_post_social_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auto_publish',
        ),
    ]
