# Generated by Django 4.2.7 on 2026-04-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_auto_publish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfiguration',
        ),
    ]
