from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    """
    Custom user model - extends Django's default User
    We keep it simple for now, can add fields later
    """
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'users'
    
    def __str__(self):
        return self.username

class Post(models.Model):
    """
    Represents a social media post
    Can be draft, scheduled, or posted
    """
    PLATFORM_CHOICES = [
        ('instagram', 'Instagram'),
        ('linkedin', 'LinkedIn'),
        ('twitter', 'Twitter'),
    ]
    
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('scheduled', 'Scheduled'),
        ('ready_to_post', 'Ready to Post'),
        ('posted', 'Posted'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    caption = models.TextField()
    hashtags = models.TextField(blank=True)
    platform = models.CharField(max_length=50, choices=PLATFORM_CHOICES, default='instagram')
    scheduled_time = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'posts'
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.user.username} - {self.platform} - {self.status}"

class ImagePrompt(models.Model):
    """
    Stores DALL-E style image prompts generated by AI
    Linked to a specific post
    """
    post = models.OneToOneField(Post, on_delete=models.CASCADE, related_name='image_prompt')
    prompt_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'image_prompts'
    
    def __str__(self):
        return f"Prompt for Post #{self.post.id}"